### ISSUE TITLE
Issue Tracker richtig nutzen

### ISSUE THREAD

**Issue by nequalstim** [nequalstim/Programmierpraktikum-SS19#1]
* [ ] Jede Aktivität ist ein Issue
* [ ] Projektfortschritt überwachen
* [ ] Aufgaben (richtig) delegieren
* [ ] Kopplung mit git (-Commits)
* [ ] Zuordnung zu Projektphasen
* [ ] Workarounds (für alles, was der IssueTracker nicht kann oder man besser ohne ihn macht
* [ ] Geeignete Labels finden
